spring:
  application:
    name: gaming-app
    version: 1.0.0-SNAPSHOT
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gamingdb
    username: root
    password: Nidhi123@
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

server:
  port: 8090
