spring:
  application:
    name: gaming-app
    version: 1.0.0-SNAPSHOT

  profiles:
    active: dev

server:
  port: 8090

---

spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gamingdb
    username: root
    password: Nidhi123@
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

---

spring:
  profiles: docker
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB